version: '3.8'
services:
  ems:
    container_name: ems-java
    environment:
      - VERSION=${VERSION}
      - MQ_HOST=${MQ_HOST}
      - MQ_PORT=${MQ_PORT}
      - MQ_USER=${MQ_USER}
      - MQ_PASS=${MQ_PASS}
      - PG_HOST=${PG_HOST}
      - PG_USER=${PG_USER}
      - PG_PASS=${PG_PASS}
      - SHOW_SQL=${SHOW_SQL}
      - FORMAT_SQL=${FORMAT_SQL}
      - LOG_LEVEL=${LOG_LEVEL}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REST_CORS_ORIGINS=${REST_CORS_ORIGINS}
      - REST_CORS_METHODS=${REST_CORS_METHODS}
      - CALLBACK_CORS_ORIGINS=${CALLBACK_CORS_ORIGINS}
    image: "ems/java:${VERSION}"
    build:
      context: .
      args:
        VERSION: "${VERSION}"
        MQ_HOST: "${MQ_HOST}"
        MQ_PORT: "${MQ_PORT}"
        MQ_USER: "${MQ_USER}"
        MQ_PASS: "${MQ_PASS}"
        PG_HOST: "${PG_HOST}"
        PG_USER: "${PG_USER}"
        PG_PASS: "${PG_PASS}"
        SHOW_SQL: "${SHOW_SQL}"
        FORMAT_SQL: "${FORMAT_SQL}"
        LOG_LEVEL: "${LOG_LEVEL}"
        REDIS_PASS: "${REDIS_PASS}"
        REDIS_HOST: "${REDIS_HOST}"
        REDIS_PORT: "${REDIS_PORT}"
        REDIS_DB: "${REDIS_DB}"
        REST_CORS_ORIGINS: "${REST_CORS_ORIGINS}"
        REST_CORS_METHODS: "${REST_CORS_METHODS}"
        CALLBACK_CORS_ORIGINS: "${CALLBACK_CORS_ORIGINS}"
    ports:
      - "${PORT}:8080"
