spring:
  liquibase:
    changeLog: classpath:db/master-changelog.yaml
    user: ${PG_USER}
    password: ${PG_PASS}
    url: ${PG_HOST}
  datasource:
    url: ${PG_HOST}
    username: ${PG_USER}
    password: ${PG_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: ${SHOW_SQL}
        format_sql: ${SHOW_SQL}
        use_sql_comments: ${SHOW_SQL}
logging:
  level:
    com.example.ems.*: ${LOG_LEVEL}
    org.hibernate.SQL: ${LOG_LEVEL}
    org.hibernate.type: ${LOG_LEVEL}
---
redis:
  cacheTtl: 3600
