spring:
  output:
    ansi:
      enabled: always
  liquibase:
    changeLog: classpath:db/master-changelog.yaml
    user: ${PG_USER}
    password: ${PG_PASS}
    url: ${PG_HOST}
  datasource:
    url: ${PG_HOST}
    username: ${PG_USER}
    password: ${PG_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: ${SHOW_SQL}
        format_sql: ${SHOW_SQL}
        use_sql_comments: ${SHOW_SQL}
logging:
  pattern:
    console: '${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(pid:${PID:- }){magenta} %clr(rid:%X{RID}){yellow} %clr(---){faint} %clr([%t]){faint} %clr(%-5logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}}'
  level:
    com.example.ems.*: ${LOG_LEVEL}
    org.hibernate.SQL: ${LOG_LEVEL}
    org.hibernate.type: ${LOG_LEVEL}
---
redis:
  cacheTtl: 3600
