spring:
  liquibase:
    changeLog: classpath:db/master-changelog.yaml
    user: ${DB_USER}
    password: ${DB_PASS}
    url: ${DB_HOST}
  datasource:
    url: ${DB_HOST}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: ${SHOW_SQL}
        format_sql: ${FORMAT_SQL}
