---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ihor Hryshkov.
--- DateTime: 8/8/20 19:16
---
redis.replicate_commands()

local hashName = KEYS[1]
local key = KEYS[2]
local value = ARGV[1]
local time = ARGV[2]

local returnValue = redis.call("HGET", hashName, key)

if (returnValue) then
    return 1;
else
    redis.call("HSET", hashName, key, value)
    redis.call("HSET", hashName .. "::expire", key, time)
    return nil;
end
